### ISSUE TITLE
报错self.dataset = self.trainer.val_dataloaders.dataset      error 'list' object has no attribute 'dataset'

### ISSUE THREAD

**Issue by M1racle-milk** [alvinliu0/HumanGaussian#13]
Epoch 0: : 100it [05:26,  3.27s/it, loss=202]                                                                                                                                             Traceback (most recent call last):                                                                                                                                    | 0/4 [00:00<?, ?it/s]
  File "/home/syy/HumanGaussian-main/launch.py", line 239, in <module>
    main(args, extras)
  File "/home/syy/HumanGaussian-main/launch.py", line 182, in main
    trainer.fit(system, datamodule=dm, ckpt_path=cfg.resume)
  File "/home/syy/.conda/envs/motionctrl/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/home/syy/.conda/envs/motionctrl/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/syy/.conda/envs/motionctrl/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home/syy/.conda/envs/motionctrl/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1103, in _run
    results = self._run_stage()
  File "/home/syy/.conda/envs/motionctrl/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1182, in _run_stage
    self._run_train()
  File "/home/syy/.conda/envs/motionctrl/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1205, in _run_train
    self.fit_loop.run()
  File "/home/syy/.conda/envs/motionctrl/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/syy/.conda/envs/motionctrl/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/home/syy/.conda/envs/motionctrl/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.on_advance_end()
  File "/home/syy/.conda/envs/motionctrl/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 250, in on_advance_end
    self._run_validation()
  File "/home/syy/.conda/envs/motionctrl/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 308, in _run_validation
    self.val_loop.run()
  File "/home/syy/.conda/envs/motionctrl/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/syy/.conda/envs/motionctrl/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/syy/.conda/envs/motionctrl/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/syy/.conda/envs/motionctrl/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 132, in advance
    self._on_evaluation_batch_start(**kwargs)
  File "/home/syy/.conda/envs/motionctrl/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 262, in _on_evaluation_batch_start
    self.trainer._call_lightning_module_hook(hook_name, *kwargs.values())
  File "/home/syy/.conda/envs/motionctrl/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1347, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/syy/HumanGaussian-main/threestudio/systems/base.py", line 156, in on_validation_batch_start
    self.dataset = self.trainer.val_dataloaders.dataset
AttributeError: 'list' object has no attribute 'dataset'

在第100次it后报错，似乎和val_dataloaders有关，需要进行怎样的修改

**Comment by alvinliu0** [comment]
你好，原先的代码是可以正常运行的。请问你是对代码/路径做了修改吗？如果代码/路径都没有修改，那可能会是环境的问题，可以参照threestudio安装依赖，再额外安装Gaussian Splatting所需要的依赖。

**Comment by M1racle-milk** [comment]
感谢你的回复，因为上一次运行报错为GaussianDreamer.on_before_optimizer_step() takes 2 positional arguments but 3 were given。
所以在GaussianDreamer368行的on_before_optimizer_step(self, optimizer): 后面加了一个参数变成on_before_optimizer_step(self, optimizer，optimizer_idx):，之后就不报这个错，变成了上面的错。
路径也只是按照说明在config文件进行模型参数与SMPL路径的更改。

**Comment by alvinliu0** [comment]
你好，

2/3个参数的报错应该是通过安装这个依赖来解决，一个修改过的differentiable gaussian rasterization，详情可见readme [installation](https://github.com/alvinliu0/HumanGaussian?tab=readme-ov-file#installation)：

```bash
# a modified gaussian splatting (+ depth, alpha rendering)
git clone --recursive https://github.com/ashawkey/diff-gaussian-rasterization
pip install ./diff-gaussian-rasterization
```

所以可以把on_before_optimizer_step那边的代码改回去，应该就能正常运行。

**Comment by M1racle-milk** [comment]
@alvinliu0 非常感谢，我去试试

**Comment by M1racle-milk** [comment]
似乎又2/3了，这个依赖之前也装过

**Comment by M1racle-milk** [comment]
我重新配置了环境，可以了，应该和CUDA与pytorch版本有关，需要高版本的。
