### ISSUE TITLE
Problem of cubvh in zero-shot animating

### ISSUE THREAD

**Issue by jamesdemon923** [alvinliu0/HumanGaussian#31]
Hi,

Thank you for your great work!

When I'm trying zero-shot animating, I have the following problem about the incompatibility in cubvh (`TypeError: create_cuBVH(): incompatible function arguments.`).

```
(HumanGaussian) root@James:/mnt/e/Project/TextGuide_Avatar/HumanGaussian# python animation.py --ply "content/sample.ply" --motion "content/Aeroplane_FW_part9.npz" --play
Number of points at loading :  531327
[INFO] load smplx from smplx_models
Traceback (most recent call last):
  File "/mnt/e/Project/TextGuide_Avatar/HumanGaussian/animation.py", line 983, in <module>
    gui.skel.load_smplx(opt.smplx_path)
  File "/mnt/e/Project/TextGuide_Avatar/HumanGaussian/animation.py", line 338, in load_smplx
    BVH = cubvh.cuBVH(self.vertices, self.faces)
  File "/root/anaconda3/envs/HumanGaussian/lib/python3.9/site-packages/cubvh/api.py", line 25, in __init__
    self.impl = _backend.create_cuBVH(vertices, triangles)
TypeError: create_cuBVH(): incompatible function arguments. The following argument types are supported:
    1. (arg0: Eigen::Ref<Eigen::Matrix<float, -1, 3, 1, -1, 3> const, 0, Eigen::OuterStride<-1> >, arg1: Eigen::Ref<Eigen::Matrix<unsigned int, -1, 3, 1, -1, 3> const, 0, Eigen::OuterStride<-1> >) -> _cubvh.cuBVH

Invoked with: array([[ 0.05463674,  0.6489572 , -0.00303048],
       [ 0.05833567,  0.6480671 , -0.00207405],
       [ 0.05902537,  0.6493742 , -0.00195028],
       ...,
       [-0.03479391,  0.6787123 ,  0.05227885],
       [-0.0328925 ,  0.67903936,  0.05117963],
       [-0.03081375,  0.6794134 ,  0.0504793 ]], dtype=float32), array([[    3,     1,     0],
       [    7,     5,     4],
       [   12,    14,    13],
       ...,
       [ 9944, 10097, 10084],
       [ 9940, 10084, 10071],
       [10071, 10058,  9932]], dtype=uint32)
```

Best,
Haolan

**Comment by jamesdemon923** [comment]
This is because cubvh is not installed correctly, follow: https://github.com/ashawkey/cubvh
